### ISSUE TITLE
Inspection/Evasion tasks roadmap

### ISSUE THREAD

**Issue by Mark2000** [AVSLab/bsk_rl#144]
These are a very popular class of RL problems for spacecraft tasking. What would we need to do to enable this type of research?

**Comment by Mark2000** [comment]
> Per #201, there should be an option to add non-agent satellites to the environment. They should just execute some default FSW mode and not be included in reward/observations/actions/etc.

On second thought, just treat these as another agent.

## TODO
### Basic thrusting
- [X] FSW for instantaneous thrust
- [X] Action for setting instantaneous thrust + duration

### High fidelity thrusting
- [ ] Thruster dynamics model
- [ ] FSW for controlling thrusters via absolute thrusts, relative OE control, etc.
- [ ] Action for realistic thruster actions

### Observations
- [X] Observations that are relative to passive satellite (how to link sats?)
- [ ] More relative observations implemented

### Scene and data
- [ ] Scene/Data for agent surface observations (lit review here)
- [ ] FSW/dyn linked to surface observations (sun incidence, etc.)
- [ ] Observation of scene (how?)
- [ ] Reward model for agent observation amount
- [ ] penalty model for use of thrust
- [ ] #105 to combine reward types
